
	<?php if (App::Config()->setting('disable_quick_links') == 'Yes'): ?>
		<?php echo App::Module('Universal_Formating')->pageFormated($page_content['id']); ?>
	<?php else: ?>
	<div class="grid_3">
		<?php  echo $this->callElement("quicklinks"); ?>
	</div>
	<div class="grid_13">
		<div class="top-col-space"></div>

		<?php echo App::Module('Universal_Formating')->pageFormated($page_content['id']);    ?>
	</div>
	<?php endif; ?>
