<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */

/**
 * Check if site live
 */
echo App::Load("Helper/Config")->isSiteLive();

$selected = isset($selected) ? $selected : "";
?><!doctype html>
<html lang="en">
  <head>
	<?php echo $this->callElement("header_info"); ?>
	<?php $this->fetchAddonlibs();?>
    <link href="<?php echo App::Config()->skinUrl("/css/default.css"); ?>" rel="stylesheet">	
  </head>
  <body>
	<?php echo $this->callElement("header"); ?>
	<main>
		<section class="container">
		<div class="row mb-2">  
		  <div class="row g-5">
			<div class="col-md-12">		
				<h1><?php echo $page_content['title']; ?></h1>
				<nav>
					<a href="<?php echo App::Config()->baseUrl() ?>">Home</a>  &gt;
					<a><?php echo $page_content['title']; ?></a>
				</nav>
		  </div>
		  </div>
		  <div class="row py-5">
			<div class="col-md-8">		
				<?php echo $content_rendered;?> 
			</div>
			<div class="col-md-4">
				<?php App::Hook('UI')->Render('template_right_column_A'); #User Interface Hook ?>
				<?php App::Hook('UI')->Render('template_right_column_B'); #User Interface Hook ?>
				<?php echo $this->callElement("quicklinks"); ?>
				<?php App::Hook('UI')->Render('template_right_column_C'); #User Interface Hook ?>
				<?php App::Hook('UI')->Render('template_right_column_D'); #User Interface Hook ?>
			</div>
		  </div>
		</div>
		</section>	  
	</main>
	<?php echo $this->callElement("footer"); ?>
	</body>
</html>
