<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please Send an email
 * to license@apprain.com so we can Send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */
 ?>
 
 <?php
/*
 *	Data as set in data helper to manage it from Pagemanager dynamic page.
 * 	It can be directly put in this template file
 */
 
/* 
 * UI Hook is to redner content from page manager set from admin panel
 */ 
?>

<?php
	App::Hook('UI')->Render('home_page_banner_top'); #User Interface Hook
	## Fetch the Homepage Slide
	echo App::View('Whitecloud')->Helper("Data")->getSlide(); 
	App::Hook('UI')->Render('home_page_banner_bottom'); #User Interface Hook
?>


<?php
	## Fetch content for Area A
	echo App::View('Whitecloud')->Helper("Data")->HomeContentAreaA(); 
	
	App::Hook('UI')->Render('home_content_area_A'); #User Interface Hook
?>

<?php
	## Fetch content for Area B
	echo App::View('Whitecloud')->Helper("Data")->HomeContentAreaB(); 
	
	App::Hook('UI')->Render('home_content_area_B'); #User Interface Hook
?>


<?php
	## Fetch content for Area C
	##echo App::View('Whitecloud')->Helper("Data")->HomeContentAreaC(); 
	
	App::Hook('UI')->Render('home_content_area_C'); #User Interface Hook
?>


<?php
	## Fetch content for Area D
	##echo App::View('Whitecloud')->Helper("Data")->HomeContentAreaD(); 
	
	App::Hook('UI')->Render('home_content_area_D'); #User Interface Hook
?>
