<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title ><?php echo App::Config()->setting('site_title'); ?></title >
    <meta  name="Keywords" content=""  />
    <meta  name="Description" content=""  />		
 </head>
  <body>
	 <?php if(App::Config()->setting('comingsoon_mode')=='Image'):?>
		<div style="text-align:center">
			<img src="<?php echo($this->baseUrl("/uploads/filemanager/" . App::Config()->setting('comingsoon_image')));?>" />
		</div>
		<?php else:?>
			<?php echo  App::Helper('Utility')->parsePHP(App::Config()->setting('comingsoon_script','<center><h1><?php echo "Coming Soon";?></h1></center>'));?>
		<?php endif;?>
  </body>
</html>