<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->callElement("default/admin_layout/header_info"); ?>
        <?php $this->fetchAddonlibs(); ?>
        <link href="<?php echo $this->baseurl("/common/default-css"); ?>" rel="stylesheet" type="text/css" media="all"/>
        <script type="text/javascript" src="<?php echo $this->baseurl("/common/default-js"); ?>"></script>
    </head>
    <body>
        <!-- header -->
        <?php if (!isset($disable_admin_header)): ?>
            <?php echo $this->callElement("default/admin_layout/admintop"); ?>
        <?php endif; ?>
        <!-- end header -->

        <!-- content -->
        <?php if (isset($admin_content_full_length) || App::Module('adminPanelUi')->isAdminLeftPancollapsed()) : ?>
            <div id="content" class="full_length">
                <?php echo $content_rendered; ?>
            </div>
        <?php elseif (isset($admin_content_clear_length)) : ?>
            <?php echo $content_rendered; ?>
        <?php else: ?>
            <div id="content">
                <table id="basetable" width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                        <td class="content-left-bg" valign="top" id="left">
                            <?php echo $this->callElement("default/admin_layout/adminleft"); ?>
                        </td>
                        <td valign="top" class="content-right" align="left">
                            <div id="right">
                                <?php App::Module('Notification')->Display(); ?>								
                                <?php echo $content_rendered; ?>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        <?php endif; ?>
        <!-- end content -->

        <!-- footer -->
        <?php if (!isset($disable_admin_footer)): ?>
            <?php echo $this->callElement("default/admin_layout/adminbottom"); ?>
        <?php endif; ?>
        <!-- end footert -->
    </body>
</html>