<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */

echo App::Config()->isSiteLive(); ?><!DOCTYPE html>
<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
		<?php App::Hook('UI')->Render('template_head_tag_start'); #User Interface Hook ?>
		<?php echo $this->callElement("header_info"); ?>

		<!-- Load by addons -->
		<?php $this->fetchAddonlibs();?>

		<!-- Static -->
		<link href="<?php echo $this->skinurl("/css/reset.css");?>" rel="stylesheet" type="text/css" media="all"/>
		<link href="<?php echo $this->skinurl("/css/default.css");?>" rel="stylesheet" type="text/css" media="all"/>
		
			
		<!-- Dynamic -->
		<link href="<?php echo $this->baseurl("/common/default-css");?>" rel="stylesheet" type="text/css" media="all"/>
		<script type="text/javascript" src="<?php echo $this->baseurl("/common/default-js");?>"></script>
		<?php App::Hook('UI')->Render('template_head_tag_end'); #User Interface Hook ?>
	</head>
	<body class="<?php echo App::Config()->Setting('whitecloud_background_position','bgdefault');?>">
		<div class="container">
			<?php  echo $this->callElement("header"); ?>
			<?php echo $content_rendered;?>				
		</div>		
		<?php echo $this->callElement("footer"); ?>	
	</body>
</html>