<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */
?>
<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */
?>

<div id="login">

    <!-- -- TITLE -- -->
    <div class="title">
        <h5><?php echo $this->__($h2);?></h5>

        <div class="corner tl"></div>
        <div class="corner tr"></div>
    </div>

    <!-- -- Message BODY --  -->
    <div class="inner" style="background:none #FFF">
        <div class="form">
            <div class="fields">
                <div class="field"> <?php echo $message ?></div>
                <div class="buttons" style="margin-top:20px">
                    <div style="float:left;margin-top:5px">
                        <a href="<?php echo $this->baseurl('/admin/forgotlogin'); ?>"><?php echo $this->__("Forgot Login?");?></a>
                    </div>
                    <input type="submit" value="View Website" onclick="window.location=siteInfo.baseUrl"/>
                    <input type="submit" value="Login" onclick="window.location=siteInfo.baseUrl + '/admin/'"/>
                </div>
            </div>
        </div>
    </div>

</div>
