<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */
?>

<?php App::Hook('UI')->Render('admin_dashboard_A'); #User Interface Hook ?>

<?php echo $this->callElement("default/admin_layout/dashboard/notificationsbox"); ?>

<?php App::Hook('UI')->Render('admin_dashboard_B'); #User Interface Hook ?>

<?php echo $this->callElement("default/admin_layout/dashboard/quicknavigation"); ?>

<?php App::Hook('UI')->Render('admin_dashboard_C'); #User Interface Hook ?>

<?php echo $this->callElement("default/admin_layout/dashboard/recentinfo"); ?>

<?php App::Hook('UI')->Render('admin_dashboard_D'); #User Interface Hook ?>