<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */
?>
<div class="admin_bars">
    <ul>
        <li class="barfirst">
            <h1>
                <?php echo app::load("Helper/Config")->load('site_info')->get('site_title'); ?>
            </h1>

            <h3 class="t-text">&nbsp;Administrative Panel</h3>
        </li>
        <li class="barsecond">&nbsp;</li>
        <li class="barthird">&nbsp;</li>
    </ul>
</div>