<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */
?>
 <div class="navbar navbar-default" role="navigation">
  <div class="container">
	<div class="navbar-header">
	  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	  </button>
	  <?php 
	  
		$logo = App::Config()->Setting("site_logo");
	  
	  
		$logo = App::Config()->Setting("site_logo");
		
		if(!empty($logo)){
		?>
			<a href="<?php echo App::Config()->baseUrl(); ?>">
			<?php echo App::Helper('Html')->imgTag(App::Config()->fileManagerUrl(DS . $logo));?>
			</a>
		<?
		}
		else{
			?>
			<a class="navbar-brand"  href="<?php echo App::Config()->baseUrl(); ?>">
			<?php echo App::Config()->Setting('site_title'); ?>
			</a>
			
		<?php
		}
		
		?>
	</div>
	<div class="navbar-collapse collapse">
		<ul class="nav navbar-nav navbar-right">
		<?php
			echo $this->siteMenuClear()
				->siteMenu($this->baseurl("/"), 'Home', 'home')
				->setRootHtmlOpts(array('class' => 'nav navbar-nav'))
				->siteMenuRender('HTML', (isset($selected) ? $selected : ""), 'active');
		?>
	  
		<?php App::Hook('UI')->Render('template_header_B'); #User Interface Hook ?>
	  </ul>
	</div>
  </div>
</div>
<?php  echo $this->callElement("breadcrumb"); ?>
