<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */

/**
 * Check if site live
 */
echo App::Load("Helper/Config")->isSiteLive();

$selected = isset($selected) ? $selected : "";
?>
<!doctype html>
<html lang="en">
  <head>
	<?php echo $this->callElement("header_info"); ?>
	<?php $this->fetchAddonlibs();?>
    <link href="<?php echo App::Config()->skinUrl("/css/default.css"); ?>" rel="stylesheet">
	
  </head>
  <body>
    

<?php echo $this->callElement("header"); ?>
<main>
	<?php 
		/*
		 *	## Render the content from inner page
		 */
		echo $content_rendered;
	?>   
</main>
<?php echo $this->callElement("footer"); ?>
</body>
</html>
