<div class="grid_8">
	<form method="post" id="flogin_form" action="<?php echo $this->baseurl("/member/passwordreset/{$restKey}"); ?>">
		<ul class="form">
			<?php
			echo App::Load("Helper/Html")->get_from_row("<div class=\"message fmessage\"></div>");	
			echo App::Load("Helper/Html")->get_from_row("New password", App::Load("Helper/Html")->passwordTag("data[Forgotlogin][new_password]", "", array("id" => "old_password", "class" => "input check_password")));
			echo App::Load("Helper/Html")->get_from_row("Confirm", App::Load("Helper/Html")->passwordTag("data[Forgotlogin][re_new_password]", "", array("id" => "old_password", "class" => "input check_password")));
			echo App::Load("Helper/Html")->get_from_row("&nbsp;", App::Load("Helper/Html")->submitTag("data[Forgotlogin][button]", "Send", array("class" => "button white medium")));
			?>
		</ul>
	</form>
	<?php App::Helper('JavaScript')->setAjax(array("debug" => true, "autoHide" => false))->appForm('#flogin_form'); ?>
</div>