<div class="well">
	<div class="input-group">
      <input type="text" class="form-control search-box" placeholder="Search for...">
      <span class="input-group-btn">
        <button class="btn btn-warning search-button" type="button">Go!</button>
      </span>
    </div>
</div>

<script type="text/javascript">
	jQuery(document).ready(function () {
		jQuery(".search-button").click(function(event) {
			var srctxt = jQuery('.search-box').val();
			if(srctxt != ''){
				window.location = siteInfo.baseUrl + '/search?ss=' + srctxt;
			}
		});
	});		
</script>
