<?php if(!empty($right_boxes['data'])):?> 
	<?php  foreach( $right_boxes['data'] as $key => $val):?>
	
	<div class="well">
		<?php if(!empty($val['image'])):?>
			<a href="<?php echo App::PageManager()->LinkById($val['linkedto']); ?>">
				<img class="thumbnail"  src="<?php echo App::Config()->filemanagerUrl("/{$val['image']}");?>" />
			</a>
		<?php endif;?>				
		<?php echo($val['shortdesc']);?>
	</div>	
	<?php endforeach;?>	
<?php endif; ?>		
	

     
