<?php if(!empty($pressdata['data'])):?>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">	   
	<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	<?php for($i=1;$i<count($pressdata['data']);$i++):?>
	<li data-target="#myCarousel" data-slide-to="<?php echo $i;?>"></li>
	<?php endfor;?>        
  </ol>
  <div class="carousel-inner">	  
	<?php foreach($pressdata['data'] as $key=>$row):?>
	<div class="item <?php if(!$key){ echo "active";} ?>">	  
	  <img src="<?php echo App::Config()->baseUrl("/componentroot/appslide/bg-slide.jpg") ?>" alt="">
	  <div class="container">
		<div class="carousel-caption">
			<div class="col-lg-6">
				<img src="<?php echo App::Helper('Config')->baseUrl("/uploads/filemanager/{$row['image']}");?>" alt="" />
			</div>
			<div class="col-lg-6">
				<?php echo ($row['description']);?>
			</div>
		</div>
	  </div>
	  
	</div>
	<?php endforeach;?> 		
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>
<?php endif; ?>