<div class="box box-left box-padding box-left-tabs">
    <div class="title">
        <h5>
		<input type="button" title="Close" class="widget-closer" id="closer_activity_widget" />
		<?php echo $this->__('System Update')?></h5>
    </div>
    <div class="inner">
        <pre>System update available</pre>
    </div>
</div>
<div class="box box-right">
    <div class="title">
        <h5>
			<input type="button" title="Close" class="widget-closer" id="closer_leave_amessage_widget" />
			<?php echo $this->__("Start Update") . App::Helper('Html')->helpTag('dashboard-appblog-quick-post');?></h5>
    </div>
    <div class="inner">
        <input type="" value="START UPDATE" class="button" />
    </div>
</div>
<br class="clearboth" />