<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */
//pre(app::$__appData['componenterr']);
?>


<?php App::Helper('Toolbar')->setTitle('Install Components')->setBtnBack()->Render(array('code' => 'install_component_top')); ?>
<br class="clearboth"/>
<?php if ($message != '') {
    echo $this->callElement('default/tools/message', array('caption' => 'Message', 'type' => 'success', 'message' => $message));
} ?>
<?php if ($error != '') {
    echo $this->callElement('default/tools/message', array('caption' => 'Error', 'type' => 'error', 'message' => $error));
} ?>
<p> Upload a component in ZIP format form your computer.</p>
<form method="post" action="<?php echo $this->baseUrl("/developer/install-component");?>" enctype="multipart/form-data">
    <input type="file" name="data[Component][resourcefile]"/>
    <input type="submit" name="submit" value="Install" class="app_button"/>
</form>
<br class="clearboth"/>
<br/>
<?php App::Helper('Toolbar')->setBtnBack()->Render(array('code' => 'install_component_bottom')); ?>