<?php $section_title = isset($section_title) ? $section_title : null; ?>
<?php if(!App::Config()->isHomePage() && isset($section_title)): ?>
	<section class="top-title">
		<div class="container">
			<div class="row-fluid">
				<div class="col-md-6">
					<h1><?php echo $section_title; ?></h1>
				</div>
				<div class="col-md-6">
					<ul class="breadcrumb pull-right">
						<li><a href="<?php echo App::Config()->baseUrl();?>">Home</a></li>
						<li class="active"><?php echo $section_title; ?></li>
					</ul>
				</div>
			</div>
		</div>
	</section>
<?php else:?>
	<section class="header-gap"></section>
<?php endif;?>