<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */
?>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="<?php echo App::Config()->filemanagerUrl("/images/favicon.ico");?>" type="image/x-icon"/>
<link rel="icon" href="<?php echo App::Config()->filemanagerUrl("/images/favicon.ico");?>" type="image/x-icon"/>
<title><?php echo  (($this->page_title != '') ? $this->page_title : ucfirst(App::Config()->Load('params')->get('action')) . (App::__Def()->SysConfig('ADMIN_PAGE_TITLE_SAPARATOR') . App::Helper('Config')->setting('site_title')));?></title>
<meta name="Keywords" content="<?php echo $this->page_meta_keyowrds;?>"/>
<meta name="Description" content="<?php echo $this->page_meta_desc;?>"/>
	