<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.com)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.com/
 *
 * Download Link
 * http://www.apprain.com/download
 *
 * Documents Link
 * http ://www.apprain.com/docs
 */
?>
     <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand"  href="<?php echo App::Config()->baseUrl(); ?>"><span class="glyphicon glyphicon-tint"></span><?php echo App::Config()->setting('site_title');?></a>
        </div>
        <div class="navbar-collapse collapse">
			<?php
				echo $this->siteMenuClear()
					->siteMenu($this->baseurl("/"), 'Home', 'home')
					->setRootHtmlOpts(array('class' => 'nav navbar-nav'))
					->siteMenuRender('HTML', (isset($selected) ? $selected : ""), 'active');
			?>
			
          <!--ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul -->
          <ul class="nav navbar-nav navbar-right">
			<?php App::Hook('UI')->Render('template_header_B'); #User Interface Hook ?>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
	
<!--div class="grid_7">&nbsp;<?php App::Hook('UI')->Render('template_header_A'); #User Interface Hook ?></div>
<div class="grid_9 align-right"><?php App::Hook('UI')->Render('template_header_B'); #User Interface Hook ?></div>
<div class="clear"></div>
<div class="grid_7 logo">	
	<?php if(App::Config()->Setting('site_logo')):?>
		<?php 
			echo App::Helper("Html")
				->linkTag(
					$this->baseurl("/"), 
					App::Helper("Html")->imgTag($this->baseUrl("/uploads/filemanager/" . App::Config()->Setting('site_logo')))
				);
		?>
	<?php else:?>
		<h2><?php echo app::load("Helper/Html")->linkTag($this->baseurl("/"), App::Config()->setting("site_title"));?></h2>
	<?php endif;?>	
</div>
<div class="grid_9 header">
	<?php
		echo $this->siteMenuClear()
			->siteMenu($this->baseurl("/"), 'Home', 'home')
			->setRootHtmlOpts(array('id' => 'menu'))
			->siteMenuRender('HTML', (isset($selected) ? $selected : ""), 'selected');
	?>
</div>
<div class="clear"></div -->