<!--==========================
      Featured Services Section
    ============================-->
	<?php echo App::View('Business')->Helper("Data")->getFeaturedServices(); ?>	
    <!-- #featured-services -->

    <!--==========================
      About Us Section
    ============================-->
	<?php echo App::View('Business')->Helper("Data")->getAboutText(); ?>	
    <!-- #about -->

    <!--==========================
      Services Section
    ============================-->
	
	<?php echo App::View('Business')->Helper("Data")->getServiceText(); ?>	
    <!-- #services -->

    <!--==========================
      Call To Action Section
    ============================-->
	
    <!-- #call-to-action -->

    

    <!--==========================
      Portfolio Section
    ============================-->
	<?php echo App::View('Business')->Helper("Data")->getPortfolio(); ?>
    <!-- #portfolio -->

    <!--==========================
      Clients Section
    ============================-->
	<?php echo App::View('Business')->Helper("Data")->getClients(); ?>
    <!-- #clients -->

    <!--==========================
      Clients Section
    ============================-->
	
	<!-- #testimonials -->
    

    <!--==========================
      Team Section
    ============================-->
	<?php echo App::View('Business')->Helper("Data")->getTeam(); ?>
    <!-- #team -->

    <!--==========================
      Contact Section
    ============================-->
	<?php echo App::View('Business')->Helper("Data")->getTeam(); ?>
	
	
	

    <section id="contact" class="section-bg wow fadeInUp">
      <div class="container">
		<?php echo App::View('Business')->Helper("Data")->getContactText(); ?>
        
		<?php /*
        <!-- div class="form">
          <div id="sendmessage">Your message has been sent. Thank you!</div>
          <div id="errormessage"></div>
          <form action="" method="post" role="form" class="contactForm">
            <div class="form-row">
              <div class="form-group col-md-6">
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                <div class="validation"></div>
              </div>
              <div class="form-group col-md-6">
                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                <div class="validation"></div>
              </div>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
              <div class="validation"></div>
            </div>
            <div class="form-group">
              <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
              <div class="validation"></div>
            </div>
            <div class="text-center"><button type="submit">Send Message</button></div>
          </form>
        </div -->*/ ?>

      </div>
    </section><!-- #contact -->
