<div class="installer-wraper">
<form method="post" action="<?php echo App::Config()->baseUrl("/updatemanager") ?>">
<?php App::Helper('Toolbar')->setTitle("System Update Complete")->setBtnBack()->Render(array('code'=>'report_manage_top')); ?>

<pre class="white_bg">
THANK YOU

System update has been complete successfully.

Please contact us any time if you need any clarification:
 Send email to <a href="mailto:info@apprain.com">info@apprain.com</a> Or Create a <a href="http://www.apprain.com/ticket">ticket</a>.
</pre>
<?php App::Helper('Toolbar')->setBtnBack()->setBtnCustomHTML('<input name="data[Install]" type="button" onclick="window.location=siteInfo.baseUrl + \'/admin\';" value="Go to Dashboard" /> <input name="data[Install]" type="button" onclick="window.location=siteInfo.baseUrl + \'/updatemanager/history\';" value="Check History" />')->Render(array('code'=>'report_manage_bottom')); ?>
</div>
</form>
