	<div class="installer-wraper">
		
		<?php  if($action == 'ready'):?>
			<?php App::Helper('Toolbar')->setTitle("RECEIVE SOURCE")->setBtnBack()->Render(array('code'=>'update_manage_top')); ?>
<pre class="white_bg">
START INSTALLATION

Patch name: <em><?php echo $SourceToInstall; ?></em>

System is ready to install, Pleaes follow below steps:
 1. Click complete button to start installation
 2. Do not click back button when installation started
</pre>			
			
			<?php App::Helper('Toolbar')->setBtnBack()->setBtnCustomHTML('<input name="data[Install]" type="button" onclick="window.location=siteInfo.baseUrl + \'//updatemanager/commit\'" value="COMPLETE >>" />')->Render(array('code'=>'update_manage_bottom')); ?>
		<?php else:?>
			<?php App::Helper('Toolbar')->setTitle("RECEIVE SOURCE")->setBtnBack()->Render(array('code'=>'update_manage_top')); ?>
			<form method="post" action="<?php echo App::Config()->baseUrl("/updatemanager/install") ?>" enctype="multipart/form-data">
<pre class="white_bg">
HELP

This process helps system update.

STEP 1:
 a. Download file from repositry
 b. Use files only certified by appRain team.
 c. Read patch manual before execution.
 
STEP 2: 
 a. Upload (only *.ZIP) file in below input box.
 b. Click "Start Installation" button
 c. Do not click becak button once installation start.
 
 Note: 
 <a href="<?php echo Component_updatemanager_Helpers_Data::REPO_URI; ?>" target="_blank">Check here</a> for appRain update 
 Check respective repositry for other updates.
</pre>
				<?php
					App::Module('DataGrid')
					->setDisplay('FormListing')
					->addRow('File',App::load("Helper/Html")->fileTag("data[UpdateManager][file]"))
					->Render();
				?>
			<?php App::Helper('Toolbar')->setBtnBack()->setBtnCustomHTML('<input name="data[Install]" type="submit" value="NEXT >>" />')->Render(array('code'=>'update_manage_bottom')); ?>
			</form>
		<?php endif;?>
</div>		