<section class="top-title">
	<div class="container">
		<div class="row-fluid">
			<div class="col-md-6">
				<h1><?php echo $staticpage['title']; ?></h1>
			</div>
			<div class="col-md-6">
				<ul class="breadcrumb pull-right">
					<li><a href="<?php echo App::Config()->baseUrl();?>">Home</a></li>
					<li class="active"><?php echo $staticpage['title']; ?></li>
				</ul>
			</div>
		</div>
	</div>
</section>
<div class="container">	  
	<div class="col-md-6">
		<?php if (isset($staticpage['content']) && $staticpage['content'] != ""): ?><?php echo $staticpage['content']; ?><?php endif;?>
	</div>
	<div class="col-md-6">
        <h2>Contact Form</h2>
		<p><span class="message"></span></p>
		<form method="post" class="app_contact form" action="<?php echo $this->baseUrl("/contactus"); ?>">
            <div class="form-group"><input type="text" name="data[Contact][f_name]" class="form-control check_notempty" placeholder="Please enter First Name." value="" /></div>					
            <div class="form-group"><input type="text" name="data[Contact][l_name]" class="form-control check_notempty" placeholder="Please enter Last Name." value="" /></div>					
            <div class="form-group"><input type="text" name="data[Contact][subject]" class="form-control check_notempty" placeholder="Please enter Subject" value="" /></div>					
            <div class="form-group"><input type="text" name="data[Contact][email]" class="form-control check_email" placeholder="Please enter Email Address" value="" /></div>					
            <div class="form-group"><textarea name="data[Contact][message]" class="form-control check_notempty" placeholder="Please type a Message"></textarea></div>					
            <div class="form-group"><?php echo App::Helper('Html')->capachaTag("contactus", Array("bk_color" => "#111111", "font_color" => "#FFFFFF"));?></div>					
            <div class="form-group"><input type="text" name="data[Contact][capacha]" class="form-control check_notempty" placeholder="Please fill in the text display in the image" value="" /></div>					
            <div class="form-group"><input type="submit" name="data[Contact][submit]" class="btn btn-default" value="Submit" /></div>
		</form>
		<?php  App::Helper('JavaScript')->setAjax(array("debug" => false, "autoHide" => true))->appForm('.app_contact');?>
	</div>
</div>