<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */
?>

<div class="container">
  <?php App::Hook('UI')->Render('template_footer_A'); #User Interface Hook ?>
  <footer class="py-5">
    <div class="row">
		<?php
			## Fetch Footer menu
			echo App::View('Whitecloud')->Helper("Data")->getFooterMenu(); ?>

		<?php
			## Fetch Footer menu
			echo App::View('Whitecloud')->Helper("Data")->getFooterContent(); ?>

    </div>
	
		
    <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
		<p>&copy; <?php echo App::Helper('Config')->setting('copy_right_text');?></p>
    </div>
	<?php App::Hook('UI')->Render('template_footer_B'); #User Interface Hook ?>
  </footer>
</div>