<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.com)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.com/
 *
 * Download Link
 * http://www.apprain.com/download
 *
 * Documents Link
 * http ://www.apprain.com/docs
 */
?>
<?php if (App::Helper('Config')->setting('whitecloud_disable_footer') != 'Yes'): ?>
<div id="footer">
	<div class="container_16">
		<div class="grid_8">
			<?php App::Hook('UI')->Render('template_footer_A'); #User Interface Hook ?>
			<?php echo App::Helper('Config')->setting('copy_right_text');?>	
		</div>
		<div class="grid_8 align-right">
			<?php App::Hook('UI')->Render('template_footer_menu'); #User Interface Hook ?>
			<?php App::Hook('UI')->Render('template_footer_B'); #User Interface Hook ?>
		</div>
		<div class="clear"></div>
	</div>
</div>
<?php endif;?>
