<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.com)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.com/
 *
 * Download Link
 * http://www.apprain.com/download
 *
 * Documents Link
 * http ://www.apprain.com/docs
 */
?>
<div class="grid_7">&nbsp;<?php App::Hook('UI')->Render('template_header_A'); #User Interface Hook ?></div>
<div class="grid_9 align-right"><?php App::Hook('UI')->Render('template_header_B'); #User Interface Hook ?></div>
<div class="clear"></div>
<div class="grid_7 logo">	
	<?php if(App::Config()->Setting('site_logo')):?>
		<?php 
			echo App::Helper("Html")
				->linkTag(
					$this->baseurl("/"), 
					App::Helper("Html")->imgTag($this->baseUrl("/uploads/filemanager/" . App::Config()->Setting('site_logo')))
				);
		?>
	<?php else:?>
		<h2><?php echo app::load("Helper/Html")->linkTag($this->baseurl("/"), App::Config()->setting("site_title"));?></h2>
	<?php endif;?>	
</div>
<div class="grid_9 header">
	<?php
		echo $this->siteMenuClear()
			->siteMenu($this->baseurl("/"), 'Home', 'home')
			->setRootHtmlOpts(array('id' => 'menu'))
			->siteMenuRender('HTML', (isset($selected) ? $selected : ""), 'selected');
	?>
</div>
<div class="clear"></div>