<section class="top-title">
	<div class="container">
		<div class="row-fluid">
			<div class="col-md-6">
				<h1><?php echo $page_content['title']; ?></h1>
			</div>
			<div class="col-md-6">
				<ul class="breadcrumb pull-right">
					<li><a href="<?php echo App::Config()->baseUrl();?>">Home</a></li>
					<li class="active"><?php echo $page_content['title']; ?></li>
				</ul>
			</div>
		</div>
	</div>
</section>
<div class="container">
<?php if (App::Config()->setting('disable_quick_links') == 'Yes'): ?>
	<?php echo App::Module('Universal_Formating')->pageFormated($page_content['id']); ?>
<?php else: ?>
<div class="col-md-3">
    <?php  echo $this->callElement("quicklinks"); ?>
</div>
<div class="col-md-9">
    <?php echo App::Module('Universal_Formating')->pageFormated($page_content['id']);    ?>
</div>
<?php endif; ?>
</div>