<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */
?>
<?php $type = isset($type) ? $type : "message"; ?>
<?php $rows = is_array($message) ? $message : array($message); ?>

<?php if (!empty($message)): ?>
<?php $type = ($type == 'message') ? 'notice' : $type; ?>
<?php foreach ($rows as $row): ?>
    <?php echo App::Module('Notification')->toHtml($row, $type); ?>
    <?php endforeach; ?>
<?php endif; ?>