<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */

echo App::Config()->isSiteLive(); ?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
 
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
 
  <?php App::Hook('UI')->Render('template_head_tag_start'); #User Interface Hook ?>
    <?php echo $this->callElement("header_info"); ?>

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="<?php echo App::Config()->skinUrl("/"); ?>lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="<?php echo App::Config()->skinUrl("/"); ?>lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="<?php echo App::Config()->skinUrl("/"); ?>lib/animate/animate.min.css" rel="stylesheet">
  <link href="<?php echo App::Config()->skinUrl("/"); ?>lib/ionicons/css/ionicons.min.css" rel="stylesheet">
  <link href="<?php echo App::Config()->skinUrl("/"); ?>lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="<?php echo App::Config()->skinUrl("/"); ?>lib/lightbox/css/lightbox.min.css" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="<?php echo App::Config()->skinUrl("/"); ?>css/default.css" rel="stylesheet">

</head>

<body>

  <!--==========================
    Header
  ============================-->
  <header id="header">
    <div class="container-fluid">
<?php

	$site_logo = App::Config()->siteInfo('site_logo');
?>
      <div id="logo" class="pull-left">
	  <?php if(empty($site_logo)): ?>
        <h1><a href="<?php echo App::Config()->baseUrl() ?>#intro" class="scrollto"><?php echo App::Config()->Setting("site_title"); ?></a></h1>
	<?php else:?>
        <a href="#intro"><img src="<?php echo App::Config()->filemanagerUrl("/{$site_logo}"); ?>" alt="" title="" /></a>
	<?php endif;?>
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active"><a href="<?php echo App::Config()->baseUrl() ?>#intro">Home</a></li>
          <li><a href="#about">About Us</a></li>
        </ul>
      </nav><!-- #nav-menu-container -->
    </div>
  </header><!-- #header -->

  <!--==========================
    Intro Section
  ============================-->
  <section id="intro">
    <div class="intro-container">
      <div id="introCarousel" class="carousel  slide carousel-fade" data-ride="carousel">

        <ol class="carousel-indicators"></ol>

        <div class="carousel-inner" role="listbox">

          <div class="carousel-item active">
            <div class="carousel-background"><img src="<?php echo App::Config()->skinUrl("/img/"); ?>intro-carousel/1.jpg" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>appRain Version 4.0.5</h2>
                <p>Compatible with PHP 7. One of the great feature of this version is buitl in web service can connect with mobile and external device. We have widely implemented it with android OS for appRain ERP implementation.   </p>
                <a href="http://www.apprain.org" class="btn-get-started scrollto">Download(4.0.5)</a>
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <div class="carousel-background"><img src="<?php echo App::Config()->skinUrl("/img/"); ?>intro-carousel/2.jpg" alt=""></div>
            <div class="carousel-container">
              <div class="carousel-content">
                <h2>appRain ERP</h2>
                <p>
				appRain ERP is an enterprise resource planing solution that offer customized and ready to use solution. This solution is available both in cloud or hosted in house. This is an initiative to create entrepreneur and assist entrepreneurs.</p>
                <a href="http://www.apprain.com" class="btn-get-started scrollto">Get Started</a>
              </div>
            </div>
          </div>
		  </div>
        <a class="carousel-control-prev" href="#introCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon ion-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>

        <a class="carousel-control-next" href="#introCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon ion-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>

      </div>
    </div>
  </section><!-- #intro -->

  <main id="main">

    <!--==========================
      Featured Services Section
    ============================-->
    <section id="featured-services">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 box">
            <i class="ion-ios-bookmarks-outline"></i>
            <h4 class="title"><a href="">LOW COST</a></h4>
            <p class="description">
			P500 is mobile version of the ERP, this cost altogether 1000BDT which is much lower then around PC base implementation.</p>
          </div>

          <div class="col-lg-4 box box-bg">
            <i class="ion-ios-stopwatch-outline"></i>
            <h4 class="title"><a href="">More Sales</a></h4>
            <p class="description">
			Under p500, we are offering free sales promotion in Market place and Social networks for free to boast sales. </p>
          </div>

          <div class="col-lg-4 box">
            <i class="ion-ios-heart-outline"></i>
            <h4 class="title"><a href="">FEE E-COMMERCE</a></h4>
            <p class="description">
			Each customer get a free e-commerce website with direct integration with POS devise to communicate with customers.</p>
          </div>

        </div>
      </div>
    </section><!-- #featured-services -->

    <!--==========================
      About Us Section
    ============================-->
    <section id="about">
      <div class="container">

        <header class="section-header">
          <h3>About Us</h3>
          <p> We offer ERP solution under  below three projects  </p>
		  
        </header>

        <div class="row about-cols">

          <div class="col-md-4 wow fadeInUp">
            <div class="about-col">
              <div class="img">
                <img src="<?php echo App::Config()->skinUrl("/img/"); ?>about-plan.jpg" alt="" class="img-fluid">
                <div class="icon"><i class="ion-ios-speedometer-outline"></i></div>
              </div>
              <h2 class="title"><a href="#">Generic ERP</a></h2>
              <p>
                This is ready solution with 30 modules for your organization. We offer POS, Inventory, HRMS, Accounting and automation of any business. System runs in could system under location network.
              </p>
            </div>
          </div>

          <div class="col-md-4 wow fadeInUp" data-wow-delay="0.1s">
            <div class="about-col">
              <div class="img">
                <img src="<?php echo App::Config()->skinUrl("/img/"); ?>about-mission.jpg" alt="" class="img-fluid">
                <div class="icon"><i class="ion-ios-list-outline"></i></div>
              </div>
              <h2 class="title"><a href="#">P500</a></h2>
              <p>
				P500 is Mobile platform which is connect with could ERP network. This is compact in a single device for scan Barcode, Print Invoice, Process Purchase order etc. This fairly a low cost solution.
              </p>
            </div>
          </div>

          <div class="col-md-4 wow fadeInUp" data-wow-delay="0.2s">
            <div class="about-col">
              <div class="img">
                <img src="<?php echo App::Config()->skinUrl("/img/"); ?>about-vision.jpg" alt="" class="img-fluid">
                <div class="icon"><i class="ion-ios-eye-outline"></i></div>
              </div>
              <h2 class="title"><a href="#">Customized Solution</a></h2>
              <p>
				This is a large scale implementation considering more customized solution. This implementation is focused on requirement analysis defined by end user by offering in house implementation. 
              </p>
            </div>
          </div>

        </div>

      </div>
    </section><!-- #about -->
  </main>

  <!--==========================
    Footer
  ============================-->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-info">
            <h3><a href="<?php echo App::Config()->baseUrl() ?>"><?php echo App::Config()->Setting("site_title"); ?></a></h3>
            <p>
			
			appRain ERP is an enterprise solution that helps to automate your business. Professional service being ensured through localized support.</p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="ion-ios-arrow-right"></i> <a href="<?php echo App::Config()->baseUrl() ?>#intro">Home</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="#about">About us</a></li>
              <li><i class="ion-ios-arrow-right"></i> <a href="<?php echo App::Config()->baseUrl("/p500-help") ?>">P500 Help</a></li>
		  
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              3/16, Baily Road <br>
              Dhaka, 1202<br>
              Bangladesh <br>
              <strong>Phone:</strong> +88 01947 403 818<br>
              <strong>Email:</strong> info@apprain.com<br>
            </p>

            
          </div>

          <div class="col-lg-3 col-md-6 footer-newsletter">
            <h4>Our Partners</h4>
            <p>
			appRain ERP is a product of Apprain Technologies, all local supports is being provided by our partners companies as our activities are mostly technical. For any query or to be our partner please contact with us.  		
			</p>
            
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>appRain Technologies</strong>. All Rights Reserved
      </div>
      <div class="credits">
       
        Template Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- #footer -->

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <!-- Uncomment below i you want to use a preloader -->
  <!-- <div id="preloader"></div> -->

  <!-- JavaScript Libraries -->
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/jquery/jquery.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/jquery/jquery-migrate.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/easing/easing.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/superfish/hoverIntent.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/superfish/superfish.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/wow/wow.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/waypoints/waypoints.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/counterup/counterup.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/owlcarousel/owl.carousel.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/isotope/isotope.pkgd.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/lightbox/js/lightbox.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/touchSwipe/jquery.touchSwipe.min.js"></script>
  <!-- Contact Form JavaScript File -->
  <script src="<?php echo App::Config()->skinUrl("/"); ?>contactform/contactform.js"></script>

  <!-- Template Main Javascript File -->
  <script src="<?php echo App::Config()->skinUrl("/"); ?>js/main.js"></script>

</body>
</html>
