<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */

echo App::Config()->isSiteLive(); ?>    

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
 
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
 
  <?php App::Hook('UI')->Render('template_head_tag_start'); #User Interface Hook ?>
    <?php echo $this->callElement("header_info"); ?>

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="<?php echo App::Config()->skinUrl("/"); ?>lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="<?php echo App::Config()->skinUrl("/"); ?>lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="<?php echo App::Config()->skinUrl("/"); ?>lib/animate/animate.min.css" rel="stylesheet">
  <link href="<?php echo App::Config()->skinUrl("/"); ?>lib/ionicons/css/ionicons.min.css" rel="stylesheet">
  <link href="<?php echo App::Config()->skinUrl("/"); ?>lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
  <link href="<?php echo App::Config()->skinUrl("/"); ?>lib/lightbox/css/lightbox.min.css" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="<?php echo App::Config()->skinUrl("/"); ?>css/style.css" rel="stylesheet">

</head>

<body>

  <!--==========================
    Header
  ============================-->
  <header id="header">
    <div class="container-fluid">
<?php

	$site_logo = App::Config()->siteInfo('site_logo');
?>
      <div id="logo" class="pull-left">
	  <?php if(empty($site_logo)): ?>
        <h1><a href="<?php echo App::Config()->baseUrl() ?>#intro" class="scrollto"><?php echo App::Config()->Setting("site_title"); ?></a></h1>
	<?php else:?>
        <!-- Uncomment below if you prefer to use an image logo -->
        <a href="#intro"><img src="<?php echo App::Config()->filemanagerUrl("/{$site_logo}"); ?>" alt="" title="" /></a>
	<?php endif;?>
      </div>
		<?php echo App::View('Business')->Helper("Data")->getMenu(); ?>
    </div>
  </header><!-- #header -->

  <!--==========================
    Intro Section
  ============================-->
  <?php if(App::Config()->isHomePage() ): ?>
	<?php echo App::View('Business')->Helper("Data")->getSlide(); ?>
  <?php endif;?>
  
  
  <main id="main">
	<?php echo $content_rendered;?>    
  </main>

  <!--==========================
    Footer
  ============================-->
  <footer id="footer">
	<?php echo App::View('Business')->Helper("Data")->bottomText(); ?>    

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><?php echo App::Config()->Setting('site_title'); ?></strong>. All Rights Reserved
      </div>
      <div class="credits">
		Developed by <a href="https://www.apprain.com">Apprain Technologies</a>
        Template Designed by <a href="https://www.bootstrapmade.com">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- #footer -->

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <!-- Uncomment below i you want to use a preloader -->
  <!-- <div id="preloader"></div> -->

  <!-- JavaScript Libraries -->
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/jquery/jquery.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/jquery/jquery-migrate.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/easing/easing.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/superfish/hoverIntent.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/superfish/superfish.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/wow/wow.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/waypoints/waypoints.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/counterup/counterup.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/owlcarousel/owl.carousel.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/isotope/isotope.pkgd.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/lightbox/js/lightbox.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/"); ?>lib/touchSwipe/jquery.touchSwipe.min.js"></script>
  <!-- Contact Form JavaScript File -->
  <script src="<?php echo App::Config()->skinUrl("/"); ?>contactform/contactform.js"></script>

  <!-- Template Main Javascript File -->
  <script src="<?php echo App::Config()->skinUrl("/"); ?>js/main.js"></script>

</body>
</html>
