<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <?php echo $this->callElement("header_info"); ?>

  <!-- Favicons -->
  <link href="<?php echo App::Config()->skinUrl("/assets/"); ?>img/favicon.png" rel="icon">
  <link href="<?php echo App::Config()->skinUrl("/assets/"); ?>img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="<?php echo App::Config()->skinUrl("/assets/"); ?>vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="<?php echo App::Config()->skinUrl("/assets/"); ?>vendor/aos/aos.css" rel="stylesheet">
  <link href="<?php echo App::Config()->skinUrl("/assets/"); ?>vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="<?php echo App::Config()->skinUrl("/assets/"); ?>vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="<?php echo App::Config()->skinUrl("/assets/"); ?>vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="<?php echo App::Config()->skinUrl("/assets/"); ?>vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  <link href="<?php echo App::Config()->skinUrl("/assets/"); ?>css/style.css" rel="stylesheet">

</head>

<body>

  <?php $site_logo = App::Config()->siteInfo('site_logo');?>
  
  <header id="header" class="fixed-top d-flex align-items-center <?php if(App::Config()->isHomePage() ): ?>header-transparent<?php endif;?>">
    <div class="container-fluid">
      <div class="row justify-content-center align-items-center">
        <div class="col-xl-11 d-flex align-items-center justify-content-between">
			<?php if(empty($site_logo)): ?>
				<h1 class="logo"><a href="<?php echo App::Config()->baseUrl() ?>"><?php echo App::Config()->Setting("site_title"); ?></a></h1>
			<?php else:?>
				<a href="<?php echo App::Config()->baseUrl() ?>" class="logo"><img src="<?php echo App::Config()->filemanagerUrl("/{$site_logo}"); ?>" alt="<?php echo App::Config()->Setting("site_title"); ?>" class="img-fluid"></a>
			<?php endif;?>
				<?php echo App::View('Business')->Helper("Data")->getMenu(); ?>
          
        </div>
      </div>

    </div>
  </header>
  
	<?php if(App::Config()->isHomePage() ): ?>
		<?php echo App::View('Business')->Helper("Data")->getSlide(); ?>
	<?php endif;?>
  
  
	<main id="main">
		<?php echo $content_rendered;?>    
	</main>


  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-info">
            <h3>BizPage</h3>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus. Scelerisque felis imperdiet proin fermentum leo. Amet volutpat consequat mauris nunc congue.</p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>

            <div class="social-links">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>

          </div>

          <div class="col-lg-3 col-md-6 footer-newsletter">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna veniam enim veniam illum dolore legam minim quorum culpa amet magna export quem marada parida nodela caramase seza.</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>BizPage</strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!--
        All the links in the footer should remain intact.
        You can delete the links only if you purchased the pro version.
        Licensing information: https://bootstrapmade.com/license/
        Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=BizPage
      -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  <!-- Uncomment below i you want to use a preloader -->
  <!-- <div id="preloader"></div> -->

  <!-- Vendor JS Files -->
  <script src="<?php echo App::Config()->skinUrl("/assets/"); ?>vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/assets/"); ?>vendor/aos/aos.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/assets/"); ?>vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/assets/"); ?>vendor/glightbox/js/glightbox.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/assets/"); ?>vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/assets/"); ?>vendor/swiper/swiper-bundle.min.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/assets/"); ?>vendor/waypoints/noframework.waypoints.js"></script>
  <script src="<?php echo App::Config()->skinUrl("/assets/"); ?>vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="<?php echo App::Config()->skinUrl("/assets/"); ?>js/main.js"></script>

</body>

</html>