<?php
/**
 * appRain CMF
 *
 * LICENSE
 *
 * This source file is subject to the MIT license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/mit-license.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apprain.com so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2010 appRain, Team. (http://www.apprain.org)
 * @license    http://www.opensource.org/licenses/mit-license.php MIT license
 *
 * HELP
 *
 * Official Website
 * http://www.apprain.org/
 *
 * Download Link
 * http://www.apprain.org/download
 *
 * Documents Link
 * http ://www.apprain.org/general-help-center
 */

echo App::Config()->isSiteLive(); ?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	 <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <?php App::Hook('UI')->Render('template_head_tag_start'); #User Interface Hook ?>
    <?php echo $this->callElement("header_info"); ?>

    <!-- Load by addons -->
    <?php $this->fetchAddonlibs();?>

    <!-- Static -->
	<link href="<?php echo $this->skinurl("/css/reset.css");?>" rel="stylesheet" type="text/css" media="all"/>
    <link href="<?php echo $this->skinurl("/css/default.css");?>" rel="stylesheet" type="text/css" media="all"/>
    	
    <!-- Dynamic -->
    <link href="<?php echo $this->baseurl("/common/default-css");?>" rel="stylesheet" type="text/css" media="all"/>
    <script type="text/javascript" src="<?php echo $this->baseurl("/common/default-js");?>"></script>
    <?php App::Hook('UI')->Render('template_head_tag_end'); #User Interface Hook ?>
</head>
 <body role="document"> 
 	<?php  echo $this->callElement("header"); ?>
	<div class="container">
		<div class="col-md-3" id="column-left">
			<?php echo $this->callElement("left"); ?>
		</div>
		<div class="col-md-6" id="column-center">	
			<?php echo $content_rendered;?>	
		</div>
		<div class="col-md-3"  id="column-right">
			<?php echo $this->callElement("right"); ?>
		</div>		
		<?php echo $this->callElement("footer"); ?>		
	</div>
</body>	
</html>